import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import AuthProvider from "@/_providers/auth/AuthProvider";
import Header from "@/_components/Header";
import Loader from "@/_components/loader/Loader";

const inter = Inter({ subsets: [ 'latin' ] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={`${inter.className} flex flex-col min-h-screen w-full bg-gray-100`}>
        <AuthProvider>
            <Header/>
            <main className="grid flex-grow">
                {children}
            </main>
        </AuthProvider>
        <Loader/>
        <ToastContainer/>
        </body>
        </html>
    )
}
